// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trace.proto

package trace_models

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import encoding_binary "encoding/binary"

import io "io"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SpanType int32

const (
	SpanType_Common SpanType = 0
	SpanType_Server SpanType = 1
	SpanType_Client SpanType = 2
)

var SpanType_name = map[int32]string{
	0: "Common",
	1: "Server",
	2: "Client",
}
var SpanType_value = map[string]int32{
	"Common": 0,
	"Server": 1,
	"Client": 2,
}

func (x SpanType) Enum() *SpanType {
	p := new(SpanType)
	*p = x
	return p
}
func (x SpanType) String() string {
	return proto.EnumName(SpanType_name, int32(x))
}
func (x *SpanType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SpanType_value, data, "SpanType")
	if err != nil {
		return err
	}
	*x = SpanType(value)
	return nil
}
func (SpanType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_trace_2d9aefd8eb88c331, []int{0}
}

type Trace struct {
	ServiceType      string  `protobuf:"bytes,1,req,name=service_type,json=serviceType" json:"service_type"`
	Service          string  `protobuf:"bytes,2,req,name=service" json:"service"`
	TraceId          string  `protobuf:"bytes,3,req,name=trace_id,json=traceId" json:"trace_id"`
	Env              string  `protobuf:"bytes,4,req,name=env" json:"env"`
	Spans            []*Span `protobuf:"bytes,5,rep,name=spans" json:"spans,omitempty"`
	ContainerId      string  `protobuf:"bytes,6,opt,name=container_id,json=containerId" json:"container_id"`
	Pid              int64   `protobuf:"varint,7,opt,name=pid" json:"pid"`
	ProcessStartTime int64   `protobuf:"varint,8,opt,name=process_start_time,json=processStartTime" json:"process_start_time"`
	InstanceId       string  `protobuf:"bytes,9,opt,name=instance_id,json=instanceId" json:"instance_id"`
}

func (m *Trace) Reset()         { *m = Trace{} }
func (m *Trace) String() string { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()    {}
func (*Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_trace_2d9aefd8eb88c331, []int{0}
}
func (m *Trace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Trace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace.Merge(dst, src)
}
func (m *Trace) XXX_Size() int {
	return m.Size()
}
func (m *Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_Trace proto.InternalMessageInfo

func (m *Trace) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *Trace) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Trace) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Trace) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *Trace) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *Trace) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *Trace) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Trace) GetProcessStartTime() int64 {
	if m != nil {
		return m.ProcessStartTime
	}
	return 0
}

func (m *Trace) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type Span struct {
	SpanId               string             `protobuf:"bytes,1,req,name=span_id,json=spanId" json:"span_id"`
	ParentSpanId         string             `protobuf:"bytes,2,req,name=parent_span_id,json=parentSpanId" json:"parent_span_id"`
	OperationName        string             `protobuf:"bytes,3,req,name=operation_name,json=operationName" json:"operation_name"`
	StartTimeMillisecond int64              `protobuf:"varint,4,req,name=start_time_millisecond,json=startTimeMillisecond" json:"start_time_millisecond"`
	EndTimeMillisecond   int64              `protobuf:"varint,5,req,name=end_time_millisecond,json=endTimeMillisecond" json:"end_time_millisecond"`
	DurationMicroseconds int64              `protobuf:"varint,6,req,name=duration_microseconds,json=durationMicroseconds" json:"duration_microseconds"`
	Status               int64              `protobuf:"varint,7,req,name=status" json:"status"`
	SpanType             SpanType           `protobuf:"varint,8,req,name=span_type,json=spanType,enum=trace_models.SpanType" json:"span_type"`
	StartTimeMicrosecond int64              `protobuf:"varint,9,req,name=start_time_microsecond,json=startTimeMicrosecond" json:"start_time_microsecond"`
	ParamInt             map[string]int64   `protobuf:"bytes,20,rep,name=param_int,json=paramInt" json:"param_int,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ParamFloat           map[string]float64 `protobuf:"bytes,21,rep,name=param_float,json=paramFloat" json:"param_float,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ParamString          map[string]string  `protobuf:"bytes,22,rep,name=param_string,json=paramString" json:"param_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resource             string             `protobuf:"bytes,40,opt,name=resource" json:"resource"`
	CallServiceType      string             `protobuf:"bytes,60,opt,name=call_service_type,json=callServiceType" json:"call_service_type"`
	CallService          string             `protobuf:"bytes,61,opt,name=call_service,json=callService" json:"call_service"`
	CallResource         string             `protobuf:"bytes,62,opt,name=call_resource,json=callResource" json:"call_resource"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_trace_2d9aefd8eb88c331, []int{1}
}
func (m *Span) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Span.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(dst, src)
}
func (m *Span) XXX_Size() int {
	return m.Size()
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *Span) GetParentSpanId() string {
	if m != nil {
		return m.ParentSpanId
	}
	return ""
}

func (m *Span) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *Span) GetStartTimeMillisecond() int64 {
	if m != nil {
		return m.StartTimeMillisecond
	}
	return 0
}

func (m *Span) GetEndTimeMillisecond() int64 {
	if m != nil {
		return m.EndTimeMillisecond
	}
	return 0
}

func (m *Span) GetDurationMicroseconds() int64 {
	if m != nil {
		return m.DurationMicroseconds
	}
	return 0
}

func (m *Span) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Span) GetSpanType() SpanType {
	if m != nil {
		return m.SpanType
	}
	return SpanType_Common
}

func (m *Span) GetStartTimeMicrosecond() int64 {
	if m != nil {
		return m.StartTimeMicrosecond
	}
	return 0
}

func (m *Span) GetParamInt() map[string]int64 {
	if m != nil {
		return m.ParamInt
	}
	return nil
}

func (m *Span) GetParamFloat() map[string]float64 {
	if m != nil {
		return m.ParamFloat
	}
	return nil
}

func (m *Span) GetParamString() map[string]string {
	if m != nil {
		return m.ParamString
	}
	return nil
}

func (m *Span) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *Span) GetCallServiceType() string {
	if m != nil {
		return m.CallServiceType
	}
	return ""
}

func (m *Span) GetCallService() string {
	if m != nil {
		return m.CallService
	}
	return ""
}

func (m *Span) GetCallResource() string {
	if m != nil {
		return m.CallResource
	}
	return ""
}

func init() {
	proto.RegisterType((*Trace)(nil), "trace_models.Trace")
	proto.RegisterType((*Span)(nil), "trace_models.Span")
	proto.RegisterMapType((map[string]float64)(nil), "trace_models.Span.ParamFloatEntry")
	proto.RegisterMapType((map[string]int64)(nil), "trace_models.Span.ParamIntEntry")
	proto.RegisterMapType((map[string]string)(nil), "trace_models.Span.ParamStringEntry")
	proto.RegisterEnum("trace_models.SpanType", SpanType_name, SpanType_value)
}
func (m *Trace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trace) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.ServiceType)))
	i += copy(dAtA[i:], m.ServiceType)
	dAtA[i] = 0x12
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.Service)))
	i += copy(dAtA[i:], m.Service)
	dAtA[i] = 0x1a
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.TraceId)))
	i += copy(dAtA[i:], m.TraceId)
	dAtA[i] = 0x22
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.Env)))
	i += copy(dAtA[i:], m.Env)
	if len(m.Spans) > 0 {
		for _, msg := range m.Spans {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintTrace(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x32
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.ContainerId)))
	i += copy(dAtA[i:], m.ContainerId)
	dAtA[i] = 0x38
	i++
	i = encodeVarintTrace(dAtA, i, uint64(m.Pid))
	dAtA[i] = 0x40
	i++
	i = encodeVarintTrace(dAtA, i, uint64(m.ProcessStartTime))
	dAtA[i] = 0x4a
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.InstanceId)))
	i += copy(dAtA[i:], m.InstanceId)
	return i, nil
}

func (m *Span) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Span) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.SpanId)))
	i += copy(dAtA[i:], m.SpanId)
	dAtA[i] = 0x12
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.ParentSpanId)))
	i += copy(dAtA[i:], m.ParentSpanId)
	dAtA[i] = 0x1a
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.OperationName)))
	i += copy(dAtA[i:], m.OperationName)
	dAtA[i] = 0x20
	i++
	i = encodeVarintTrace(dAtA, i, uint64(m.StartTimeMillisecond))
	dAtA[i] = 0x28
	i++
	i = encodeVarintTrace(dAtA, i, uint64(m.EndTimeMillisecond))
	dAtA[i] = 0x30
	i++
	i = encodeVarintTrace(dAtA, i, uint64(m.DurationMicroseconds))
	dAtA[i] = 0x38
	i++
	i = encodeVarintTrace(dAtA, i, uint64(m.Status))
	dAtA[i] = 0x40
	i++
	i = encodeVarintTrace(dAtA, i, uint64(m.SpanType))
	dAtA[i] = 0x48
	i++
	i = encodeVarintTrace(dAtA, i, uint64(m.StartTimeMicrosecond))
	if len(m.ParamInt) > 0 {
		for k, _ := range m.ParamInt {
			dAtA[i] = 0xa2
			i++
			dAtA[i] = 0x1
			i++
			v := m.ParamInt[k]
			mapSize := 1 + len(k) + sovTrace(uint64(len(k))) + 1 + sovTrace(uint64(v))
			i = encodeVarintTrace(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintTrace(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x10
			i++
			i = encodeVarintTrace(dAtA, i, uint64(v))
		}
	}
	if len(m.ParamFloat) > 0 {
		for k, _ := range m.ParamFloat {
			dAtA[i] = 0xaa
			i++
			dAtA[i] = 0x1
			i++
			v := m.ParamFloat[k]
			mapSize := 1 + len(k) + sovTrace(uint64(len(k))) + 1 + 8
			i = encodeVarintTrace(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintTrace(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x11
			i++
			encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(v))))
			i += 8
		}
	}
	if len(m.ParamString) > 0 {
		for k, _ := range m.ParamString {
			dAtA[i] = 0xb2
			i++
			dAtA[i] = 0x1
			i++
			v := m.ParamString[k]
			mapSize := 1 + len(k) + sovTrace(uint64(len(k))) + 1 + len(v) + sovTrace(uint64(len(v)))
			i = encodeVarintTrace(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintTrace(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintTrace(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	dAtA[i] = 0xc2
	i++
	dAtA[i] = 0x2
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.Resource)))
	i += copy(dAtA[i:], m.Resource)
	dAtA[i] = 0xe2
	i++
	dAtA[i] = 0x3
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.CallServiceType)))
	i += copy(dAtA[i:], m.CallServiceType)
	dAtA[i] = 0xea
	i++
	dAtA[i] = 0x3
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.CallService)))
	i += copy(dAtA[i:], m.CallService)
	dAtA[i] = 0xf2
	i++
	dAtA[i] = 0x3
	i++
	i = encodeVarintTrace(dAtA, i, uint64(len(m.CallResource)))
	i += copy(dAtA[i:], m.CallResource)
	return i, nil
}

func encodeVarintTrace(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Trace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ServiceType)
	n += 1 + l + sovTrace(uint64(l))
	l = len(m.Service)
	n += 1 + l + sovTrace(uint64(l))
	l = len(m.TraceId)
	n += 1 + l + sovTrace(uint64(l))
	l = len(m.Env)
	n += 1 + l + sovTrace(uint64(l))
	if len(m.Spans) > 0 {
		for _, e := range m.Spans {
			l = e.Size()
			n += 1 + l + sovTrace(uint64(l))
		}
	}
	l = len(m.ContainerId)
	n += 1 + l + sovTrace(uint64(l))
	n += 1 + sovTrace(uint64(m.Pid))
	n += 1 + sovTrace(uint64(m.ProcessStartTime))
	l = len(m.InstanceId)
	n += 1 + l + sovTrace(uint64(l))
	return n
}

func (m *Span) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SpanId)
	n += 1 + l + sovTrace(uint64(l))
	l = len(m.ParentSpanId)
	n += 1 + l + sovTrace(uint64(l))
	l = len(m.OperationName)
	n += 1 + l + sovTrace(uint64(l))
	n += 1 + sovTrace(uint64(m.StartTimeMillisecond))
	n += 1 + sovTrace(uint64(m.EndTimeMillisecond))
	n += 1 + sovTrace(uint64(m.DurationMicroseconds))
	n += 1 + sovTrace(uint64(m.Status))
	n += 1 + sovTrace(uint64(m.SpanType))
	n += 1 + sovTrace(uint64(m.StartTimeMicrosecond))
	if len(m.ParamInt) > 0 {
		for k, v := range m.ParamInt {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTrace(uint64(len(k))) + 1 + sovTrace(uint64(v))
			n += mapEntrySize + 2 + sovTrace(uint64(mapEntrySize))
		}
	}
	if len(m.ParamFloat) > 0 {
		for k, v := range m.ParamFloat {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTrace(uint64(len(k))) + 1 + 8
			n += mapEntrySize + 2 + sovTrace(uint64(mapEntrySize))
		}
	}
	if len(m.ParamString) > 0 {
		for k, v := range m.ParamString {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTrace(uint64(len(k))) + 1 + len(v) + sovTrace(uint64(len(v)))
			n += mapEntrySize + 2 + sovTrace(uint64(mapEntrySize))
		}
	}
	l = len(m.Resource)
	n += 2 + l + sovTrace(uint64(l))
	l = len(m.CallServiceType)
	n += 2 + l + sovTrace(uint64(l))
	l = len(m.CallService)
	n += 2 + l + sovTrace(uint64(l))
	l = len(m.CallResource)
	n += 2 + l + sovTrace(uint64(l))
	return n
}

func sovTrace(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTrace(x uint64) (n int) {
	return sovTrace(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Trace) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrace
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Trace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Trace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Service", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Service = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Env = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spans = append(m.Spans, &Span{})
			if err := m.Spans[len(m.Spans)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pid", wireType)
			}
			m.Pid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pid |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessStartTime", wireType)
			}
			m.ProcessStartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProcessStartTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstanceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrace(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrace
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("service_type")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("service")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("trace_id")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("env")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Span) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrace
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Span: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Span: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpanId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpanId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentSpanId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentSpanId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeMillisecond", wireType)
			}
			m.StartTimeMillisecond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTimeMillisecond |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000008)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTimeMillisecond", wireType)
			}
			m.EndTimeMillisecond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTimeMillisecond |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000010)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DurationMicroseconds", wireType)
			}
			m.DurationMicroseconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DurationMicroseconds |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000020)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000040)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpanType", wireType)
			}
			m.SpanType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SpanType |= (SpanType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000080)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeMicrosecond", wireType)
			}
			m.StartTimeMicrosecond = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTimeMicrosecond |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000100)
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamInt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ParamInt == nil {
				m.ParamInt = make(map[string]int64)
			}
			var mapkey string
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTrace
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTrace
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTrace
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTrace
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= (int64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTrace(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTrace
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ParamInt[mapkey] = mapvalue
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamFloat", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ParamFloat == nil {
				m.ParamFloat = make(map[string]float64)
			}
			var mapkey string
			var mapvalue float64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTrace
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTrace
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTrace
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapvaluetemp uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					mapvaluetemp = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
					iNdEx += 8
					mapvalue = math.Float64frombits(mapvaluetemp)
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTrace(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTrace
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ParamFloat[mapkey] = mapvalue
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamString", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ParamString == nil {
				m.ParamString = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTrace
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTrace
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTrace
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTrace
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthTrace
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTrace(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTrace
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ParamString[mapkey] = mapvalue
			iNdEx = postIndex
		case 40:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resource", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resource = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 60:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallServiceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallServiceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 61:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallService", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallService = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 62:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallResource", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrace
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallResource = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrace(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrace
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("span_id")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("parent_span_id")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("operation_name")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("start_time_millisecond")
	}
	if hasFields[0]&uint64(0x00000010) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("end_time_millisecond")
	}
	if hasFields[0]&uint64(0x00000020) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("duration_microseconds")
	}
	if hasFields[0]&uint64(0x00000040) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("status")
	}
	if hasFields[0]&uint64(0x00000080) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("span_type")
	}
	if hasFields[0]&uint64(0x00000100) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("start_time_microsecond")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTrace(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTrace
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrace
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTrace
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTrace
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTrace(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTrace = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTrace   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("trace.proto", fileDescriptor_trace_2d9aefd8eb88c331) }

var fileDescriptor_trace_2d9aefd8eb88c331 = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0x6b, 0xdb, 0x30,
	0x14, 0x8e, 0x93, 0x26, 0x71, 0x5e, 0xd2, 0x36, 0x13, 0x6d, 0x10, 0x65, 0x73, 0x4d, 0xc7, 0x58,
	0xd6, 0x41, 0x18, 0x3d, 0x8c, 0xb5, 0xac, 0x3b, 0xb4, 0xac, 0x23, 0x83, 0x8e, 0x91, 0xf4, 0x6e,
	0x84, 0xad, 0x0d, 0x31, 0x5b, 0x36, 0x92, 0x52, 0xc8, 0xbf, 0xd8, 0x69, 0xbf, 0xa9, 0xb7, 0xf5,
	0xb8, 0xd3, 0x18, 0xed, 0x1f, 0x19, 0xb2, 0x6c, 0x47, 0x69, 0x08, 0xf4, 0x66, 0x7d, 0xdf, 0xf7,
	0xbe, 0xf7, 0xf4, 0xf1, 0x64, 0xe8, 0x2a, 0x41, 0x42, 0x3a, 0xca, 0x44, 0xaa, 0x52, 0xd4, 0xcb,
	0x0f, 0x41, 0x92, 0x46, 0x34, 0x96, 0x07, 0xbf, 0xeb, 0xd0, 0xbc, 0xd2, 0x00, 0x7a, 0x09, 0x3d,
	0x49, 0xc5, 0x35, 0x0b, 0x69, 0xa0, 0xe6, 0x19, 0xc5, 0x8e, 0x5f, 0x1f, 0x76, 0xce, 0x36, 0x6e,
	0xfe, 0xee, 0xd7, 0x26, 0xdd, 0x82, 0xb9, 0x9a, 0x67, 0x14, 0x79, 0xd0, 0x2e, 0x8e, 0xb8, 0x6e,
	0x69, 0x4a, 0x10, 0xed, 0x83, 0x6b, 0x5a, 0xb0, 0x08, 0x37, 0x6c, 0x41, 0x8e, 0x8e, 0x23, 0x34,
	0x80, 0x06, 0xe5, 0xd7, 0x78, 0xc3, 0xe2, 0x34, 0x80, 0x86, 0xd0, 0x94, 0x19, 0xe1, 0x12, 0x37,
	0xfd, 0xc6, 0xb0, 0x7b, 0x84, 0x46, 0xf6, 0xa4, 0xa3, 0x69, 0x46, 0xf8, 0xc4, 0x08, 0xf4, 0xac,
	0x61, 0xca, 0x15, 0x61, 0x9c, 0x0a, 0xdd, 0xa6, 0xe5, 0x3b, 0x8b, 0x59, 0x2b, 0xc6, 0xb4, 0xca,
	0x58, 0x84, 0xdb, 0xbe, 0x33, 0x6c, 0x94, 0xad, 0x32, 0x16, 0xa1, 0x23, 0x40, 0x99, 0x48, 0x43,
	0x2a, 0x65, 0x20, 0x15, 0x11, 0x2a, 0x50, 0x2c, 0xa1, 0xd8, 0xb5, 0x64, 0xfd, 0x82, 0x9f, 0x6a,
	0xfa, 0x8a, 0x25, 0x14, 0xbd, 0x80, 0x2e, 0xe3, 0x52, 0x11, 0x6e, 0xae, 0xd6, 0xb1, 0x7a, 0x42,
	0x49, 0x8c, 0xa3, 0x83, 0x5f, 0x2e, 0x6c, 0xe8, 0x59, 0xd1, 0x33, 0x68, 0xeb, 0x69, 0xb5, 0xd6,
	0xce, 0xb2, 0xa5, 0xc1, 0x71, 0x84, 0x0e, 0x61, 0x2b, 0x23, 0x82, 0x72, 0x15, 0x94, 0x2a, 0x3b,
	0xcd, 0x9e, 0xe1, 0xa6, 0x46, 0xfb, 0x1a, 0xb6, 0xd2, 0x8c, 0x0a, 0xa2, 0x58, 0xca, 0x03, 0x4e,
	0x12, 0xba, 0x14, 0xec, 0x66, 0xc5, 0x7d, 0x21, 0x09, 0x45, 0x27, 0x30, 0x58, 0xdc, 0x29, 0x48,
	0x58, 0x1c, 0x33, 0x49, 0xc3, 0x94, 0x47, 0x79, 0xe2, 0xe5, 0xfd, 0x76, 0x64, 0x79, 0xb1, 0xcb,
	0x85, 0x02, 0xbd, 0x85, 0x1d, 0xca, 0xa3, 0xd5, 0xca, 0xa6, 0x55, 0x89, 0x28, 0x8f, 0x1e, 0xd6,
	0x1d, 0xc3, 0x6e, 0x34, 0x2b, 0xe6, 0x4b, 0x58, 0x28, 0x52, 0x83, 0x4b, 0xdc, 0xb2, 0x5b, 0x96,
	0x92, 0x4b, 0x4b, 0x81, 0x9e, 0x42, 0x4b, 0x2a, 0xa2, 0x66, 0x12, 0xb7, 0x2d, 0x6d, 0x81, 0xa1,
	0x63, 0xe8, 0xe4, 0xf1, 0xe4, 0x2b, 0xe9, 0xfa, 0xf5, 0xe1, 0xd6, 0xd1, 0x60, 0x75, 0x2f, 0xf4,
	0x5e, 0x16, 0x85, 0xae, 0x2c, 0xce, 0x2b, 0x39, 0x54, 0x3d, 0x71, 0x67, 0x4d, 0x0e, 0x95, 0x02,
	0x9d, 0x42, 0x27, 0x23, 0x82, 0x24, 0x01, 0xe3, 0x0a, 0xef, 0xe4, 0xeb, 0xe8, 0xaf, 0xb6, 0x1d,
	0x7d, 0xd5, 0x9a, 0x31, 0x57, 0x1f, 0xb9, 0x12, 0xf3, 0x89, 0x9b, 0x15, 0x47, 0x74, 0x0e, 0x5d,
	0x53, 0xfe, 0x2d, 0x4e, 0x89, 0xc2, 0xbb, 0xb9, 0xc1, 0xc1, 0x3a, 0x83, 0x0b, 0x2d, 0x32, 0x16,
	0x90, 0x55, 0x00, 0xba, 0x80, 0x9e, 0x31, 0x91, 0x4a, 0x30, 0xfe, 0x1d, 0x0f, 0x72, 0x97, 0xe7,
	0xeb, 0x5c, 0xa6, 0xb9, 0xca, 0xd8, 0x98, 0xee, 0x06, 0x41, 0x3e, 0xb8, 0x82, 0xca, 0x74, 0x26,
	0x42, 0x8a, 0x87, 0xd6, 0xd2, 0x56, 0x28, 0x7a, 0x03, 0x4f, 0x42, 0x12, 0xc7, 0xc1, 0xd2, 0xfb,
	0x7f, 0x6f, 0x49, 0xb7, 0x35, 0x3d, 0xb5, 0xfe, 0x01, 0xfa, 0x01, 0x5a, 0x15, 0xf8, 0x74, 0xe9,
	0x01, 0x2e, 0xc4, 0xe8, 0x15, 0x6c, 0xe6, 0xc2, 0x6a, 0x82, 0x0f, 0x96, 0x32, 0xf7, 0x98, 0x14,
	0xcc, 0xde, 0x27, 0xd8, 0x5c, 0xca, 0x53, 0x3f, 0xde, 0x1f, 0x74, 0x8e, 0x1d, 0xab, 0x42, 0x03,
	0x68, 0x0f, 0x9a, 0xd7, 0x24, 0x9e, 0xe9, 0xdf, 0xcf, 0xe2, 0xbd, 0x1a, 0xe8, 0xa4, 0xfe, 0xce,
	0xd9, 0x1b, 0xc3, 0xf6, 0x83, 0x5c, 0x1f, 0x67, 0xe5, 0xac, 0x5a, 0x7d, 0x86, 0xfe, 0xc3, 0x70,
	0x1f, 0xe7, 0xd5, 0x59, 0xf1, 0x3a, 0x1c, 0x81, 0x5b, 0xee, 0x2a, 0x02, 0x68, 0x9d, 0xa7, 0x49,
	0x92, 0xf2, 0x7e, 0x4d, 0x7f, 0xeb, 0xb4, 0xa8, 0xe8, 0x3b, 0x39, 0x1e, 0x33, 0xca, 0x55, 0xbf,
	0x7e, 0x86, 0x6f, 0xee, 0x3c, 0xe7, 0xf6, 0xce, 0x73, 0xfe, 0xdd, 0x79, 0xce, 0xcf, 0x7b, 0xaf,
	0x76, 0x7b, 0xef, 0xd5, 0xfe, 0xdc, 0x7b, 0xb5, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xe5,
	0x27, 0x45, 0xd0, 0x05, 0x00, 0x00,
}
